# .github/workflows/deploy.yml
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: drhscit.org
          port: 4243
          username: vocab
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/vocab/www
            git pull origin main
            sudo systemctl restart vocab
